### ISSUE TITLE
Elite Observatory doesn't announce discoveries immediately

### ISSUE THREAD

**Issue by vanderaj** [Xjph/ObservatoryCore#125] opened 2023-11-10 17:36 UTC
I encouraged a member of my squadron to install Observatory Core. Things were going ok, but they found that the app only announced things if they clicked "Read All" or waited like 5 minutes, and it would catch up with the game. 

I made sure they had the monitor started (it was set to go at startup), and I got them to reset the location of their journal files, but no change. They decided to uninstall the app at this point, but if you have any tips or tricks to diagnose or fix the problem, please let me know and I'll pass it on.

**Comment by Xjph** [comment] 2023-12-08 03:02
Duplicate of #80

**Closed by Xjph** 2023-12-08 03:02 UTC
